"""is_active int referral

Revision ID: 24ff4b91146a
Revises: 5cec1f192eb7
Create Date: 2025-02-15 01:50:30.115491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ff4b91146a'
down_revision: Union[str, None] = '5cec1f192eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral', 'is_active')
    # ### end Alembic commands ###
